export const CHECK_LOGIN_STATUS_ACTION = 'app/LoginPage/CHECK_LOGIN_STATUS_ACTION';
export const AUTHENTICATE_ACTION = 'app/LoginPage/AUTHENTICATE_ACTION';
export const AUTHENTICATED_ACTION = 'app/LoginPage/AUTHENTICATED_ACTION';
export const LOGINMESSAGEERROR_ACTION = 'app/LoginPage/LOGINMESSAGEERROR_ACTION';
export const LOGIN_ACTION = 'app/LoginPage/LOGIN_ACTION';
export const LOGOUT_ACTION = 'app/LoginPage/LOGOUT_ACTION';

export const SIGNUP_ACTION = 'app/LoginPage/SIGNUP_ACTION';
export const SIGNUPMESSAGEERROR_ACTION = 'app/LoginPage/SIGNUPMESSAGEERROR_ACTION';
export const VERIFICATION_CODE_HAS_BEEN_SENT = 'app/LoginPage/VERIFICATION_CODE_HAS_BEEN_SENT';

export const CREATE_USER = 'app/LoginPage/CREATE_USER';
export const CHECK_USER_EXISTENCE = 'app/LoginPage/CHECK_USER_EXISTENCE';

export const UPDATE_USERNAME_ACTION = 'app/LoginPage/UPDATE_USERNAME_ACTION';
export const UPDATED_USERNAME_ACTION = 'app/LoginPage/UPDATED_USERNAME_ACTION';
export const UPDATE_USERNAME_MESSAGEERROR_ACTION = 'app/LoginPage/UPDATE_USERNAME_MESSAGEERROR_ACTION';
export const REMOVE_TOAST_FOR_UPDATED_USERNAME_ACTION = 'app/LoginPage/REMOVE_TOAST_FOR_UPDATED_USERNAME_ACTION';

export const SEND_VERIFICATION_CODE = 'app/LoginPage/SEND_VERIFICATION_CODE';
export const VERIFY_CODE_SENT_BY_SMS = 'app/VerifySmsCodePage/VERIFY_CODE_SENT_BY_SMS';
export const REMOVE_ERROR_MESSAGE_FROM_ADD_PAGE = 'app/VerifySmsCodePage/REMOVE_ERROR_MESSAGE_FROM_ADD_PAGE';
