export const CREATE_NOTIFICATION = 'CREATE_NOTIFICATION';
export const CREATE_NOTIFICATION_SUCCESS = 'CREATE_NOTIFICATION_SUCCESS';
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const SHOW_ERROR = 'SHOW_ERROR';
export const SET_NOTIFICATIONS_SEEN = 'SET_NOTIFICATIONS_SEEN';
export const SET_NOTIFICATIONS_SEEN_SUCCESS = 'SET_NOTIFICATIONS_SEEN_SUCCESS';
