export const GET_SINGLE_WISHLIST_ACTION = 'GET_SINGLE_WISHLIST_ACTION';
export const GET_SINGLE_WISHLIST_SUCCESS_ACTION = 'GET_SINGLE_WISHLIST_SUCCESS_ACTION';
export const GET_SINGLE_WISHLIST_FAILURE_ACTION = 'GET_SINGLE_WISHLIST_FAILURE_ACTION';

export const GET_WISHLISTS_FOR_UPDATE_ACTION = 'GET_WISHLISTS_FOR_UPDATE_ACTION';
export const GET_WISHLISTS_FOR_UPDATE_SUCCESS_ACTION = 'GET_WISHLISTS_FOR_UPDATE_SUCCESS_ACTION';
export const WISHLISTS_FOR_UPDATE_CALLBACK_ACTION = 'WISHLISTS_FOR_UPDATE_CALLBACK_ACTION';

export const GET_WISHLISTS_ACTION = 'GET_WISHLISTS_ACTION';
export const GET_WISHLISTS_SUCCESS_ACTION = 'GET_WISHLISTS_SUCCESS_ACTION';
export const GET_WISHLISTS_FAILURE_ACTION = 'GET_WISHLISTS_FAILURE_ACTION';

export const GET_FRIEND_WISHLISTS_ACTION = 'GET_FRIEND_WISHLISTS_ACTION';
export const GET_FRIEND_WISHLISTS_SUCCESS_ACTION = 'GET_FRIEND_WISHLISTS_SUCCESS_ACTION';
export const GET_FRIEND_WISHLISTS_FAILURE_ACTION = 'GET_FRIEND_WISHLISTS_FAILURE_ACTION';

export const CREATE_WISHLIST_ACTION = 'CREATE_WISHLIST_ACTION';
export const CREATED_WISHLIST_ACTION = 'CREATED_WISHLIST_ACTION';
export const CREATE_WISHLIST_MESSAGEERROR_ACTION = 'CREATE_WISHLIST_MESSAGEERROR_ACTION';

export const UPDATE_WISHLIST_ACTION = 'UPDATE_WISHLIST_ACTION';
export const UPDATED_WISHLIST_ACTION = 'UPDATED_WISHLIST_ACTION';
export const UPDATE_WISHLIST_MESSAGEERROR_ACTION = 'UPDATE_WISHLIST_MESSAGEERROR_ACTION';

export const REMOVE_WISHLIST_ACTION = 'REMOVE_WISHLIST_ACTION';
export const REMOVED_WISHLIST_ACTION = 'REMOVED_WISHLIST_ACTION';
export const REMOVE_WISHLIST_MESSAGEERROR_ACTION = 'REMOVE_WISHLIST_MESSAGEERROR_ACTION';

export const CREATE_WISH_ACTION = 'CREATE_WISH_ACTION';
export const CREATED_WISH_ACTION = 'CREATED_WISH_ACTION';
export const CREATE_WISH_MESSAGEERROR_ACTION = 'CREATE_WISH_MESSAGEERROR_ACTION';

export const REMOVE_WISH_ACTION = 'REMOVE_WISH_ACTION';
export const REMOVED_WISH_ACTION = 'REMOVED_WISH_ACTION';
export const REMOVE_WISH_MESSAGEERROR_ACTION = 'REMOVE_WISH_MESSAGEERROR_ACTION';

export const SELECT_WISHLIST_ACTION = 'SELECT_WISHLIST_ACTION';
export const SELECT_WISHLIST_ITEM_ACTION = 'SELECT_WISHLIST_ITEM_ACTION';

export const UPLOAD_WISH_IMAGE_ACTION = 'UPLOAD_WISH_IMAGE_ACTION';
export const UPLOADED_WISH_IMAGE_ACTION = 'UPLOADED_WISH_IMAGE_ACTION';
export const UPLOAD_WISH_IMAGE_ERROR_ACTION = 'UPLOAD_WISH_IMAGE_ERROR_ACTION';

